language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - extra-android-support
    - build-tools-29.0.2
    - android-29
    - sys-img-armeabi-v7a-android-18
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"
jdk:
  - oraclejdk8
before_script:
  - touch local.properties
  - echo "storeFile=/\n" >> local.properties
  - echo "storePassword=a\n" >> local.properties
  - echo "keyAlias=b\n" >> local.properties
  - echo "keyPassword=c\n" >> local.properties
script:
  - ./gradlew clean testDebugUnitTest
notifications:
  email: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache